### ISSUE TITLE
Use <=> operator in Timestamp class for order comparison

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-filter-collate#2]
`@collatingArray.sort! { |eventA, eventB| eventB.timestamp.to_i <=> eventA.timestamp.to_i }` is used temporarily until https://github.com/elasticsearch/logstash/issues/2052 is fixed

**Comment by jsvd** [comment]
elastic/logstash#2061 that included <=> delegation from LogStash::Timestamp to Time has been merged into master
